name: 📊 Hesaplama / Bakiye Yanlış
description: "Rakamlar tutmuyor, hesap yanlış" diyorsanız.
title: "[HESAP] "
labels: ["data-integrity", "critical", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📊 Hesaplama Hatası Bildirimi
        "Burası 100 TL olması gerekirken 90 TL çıkıyor" gibi durumları buradan bildirin.

  - type: input
    id: license
    attributes:
      label: Müşteri No / Lisans Anahtarı
      description: Destek paketinizin doğrulanması için gereklidir.
      placeholder: "Örn: GULSEN-2024-XXXX"
    validations:
      required: true
  
  - type: dropdown
    id: impact
    attributes:
      label: Hata Nerede?
      options:
        - Muhasebe Bakiyesi Yanlış (Kritik)
        - Stok Miktarı Yanlış
        - Rapordaki Toplam Yanlış
        - Fatura KDV/Toplam Hesabı Yanlış
        - Diğer

  - type: input
    id: record_ref
    attributes:
      label: Hangi Kayıtta?
      description: Sorunlu olan Fatura No, Sipariş No veya Stok Kodu nedir?
      placeholder: "FAT-2024-00123..."
    validations:
      required: true

  - type: textarea
    id: calculation
    attributes:
      label: Ne Olması Gerekiyordu?
      description: |
        Sizce doğru rakam ne? Program ne gösteriyor?
        Örnek: "Alt toplam 100 TL, KDV 20 TL iken Toplam 120 TL olmalı ama 118 TL yazıyor."
      placeholder: "Doğrusu: ... , Programdaki Hatalı: ..."
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Resim / Ekran Görüntüsü
      description: Yanlış olan yerin resmini buraya yapıştırın.
      placeholder: "Resmi buraya yapıştırın (CTRL+V)..."
    validations:
      required: false
