name: ⚡ Program Yavaş Çalışıyor
description: "Çok bekletiyor, donuyor" dediğiniz durumlar için.
title: "[HIZ] "
labels: ["performance", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Yavaşlık Bildirim Formu
        Hangi işlemin yavaş olduğunu bulmamız için bize yardımcı olun.

  - type: input
    id: license
    attributes:
      label: Müşteri No / Lisans Anahtarı
      description: Destek paketinizin doğrulanması için gereklidir.
      placeholder: "Örn: GULSEN-2024-XXXX"
    validations:
      required: true
  
  - type: dropdown
    id: scope
    attributes:
      label: Kimde Sorun Var?
      description: Sadece sizde mi yoksa herkeste mi yavaş?
      options:
        - Sadece benim bilgisayarımda
        - Ofisteki birkaç kişide
        - Tüm şirkette sistem yavaş
    validations:
      required: true

  - type: dropdown
    id: where
    attributes:
      label: Ne Yaparken Yavaşlıyor?
      description: En çok hangi işlemde bekletiyor?
      options:
        - Programa Giriş Yaparken (Login)
        - Kaydet Butonuna Basınca
        - Rapor Çekerken / Listeleme Yaparken
        - Arama Yaparken
        - Sayfa Geçişlerinde
        - Diğer
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detaylı Açıklama
      description: Mesela "Fatura listesini açarken bazen 1 dakika bekliyorum" gibi yazabilirsiniz.
      placeholder: "Fatura listesini açtığımda verilerin gelmesi yaklaşık 20 saniye sürüyor..."
    validations:
      required: true
